import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EBK User Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children,session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider session={session}>

        {children}
      </AuthProvider>
      </body>
    </html>
  );
}
